# THIS FILE SHOULD NOT BE EDITED
# ALL APPLICATION CONFIGURATION MUST BE IN CONFIG SERVER
# THIS FILE ONLY CONTAINS "STRUCTURAL" CONFIGURATION AND MUST NOT BE CHANGED

info:
  version: 1.0
  title: hazelcastTaskDistributor
server:
  port: 8181
management:
  context-path: /manage
  security:
    enabled: false


# Swagger specification path
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

# Jackson serialization library: date serialization configuration
jackson:
  serialization:
    write_dates_as_timestamps: false

logging:
  config: classpath:log4j2.xml
# PROFILE LOCAL  #
---
spring:
  profiles: gemFireNodeName
  gemfire:
    name: gemFireNodeName
    start-locator: localhost[10334]
    locators: localhost[10335]
    manager:
      port: 1099
      start: true

---
spring:
  profiles: gemFireNodeName2
  gemfire:
    name: gemFireNodeName
    start-locator: localhost[10335]
    locators: localhost[10334]
    manager:
      port: 1199
      start: true